### ISSUE TITLE
--std flag not working

### ISSUE THREAD

**Issue by willwray** [friendlyanon/cmake-init#15]
From a fresh install, all attempts to use the `--std` flag are failing

```
$ uname -a
Linux user 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 2021 x86_64 x86_64 x86_64 GNU/Linux

$ pip install --user cmake-init
...
Successfully installed cmake-init-0.20.4
```

```
$ cmake-init -h .
...
You are all set. Have fun programming and create something awesome!
```

```
$ cmake-init -h --std c++17 .
Traceback (most recent call last):
  File "/home/user/.local/bin/cmake-init", line 8, in <module>
    sys.exit(pypi_main())
  File "/home/user/.local/lib/python3.8/site-packages/cmake_init_lib/__init__.py", line 14, in pypi_main
    main(zip)
  File "/home/user/.local/lib/python3.8/site-packages/cmake_init_lib/cmake_init.py", line 489, in main
    create(args, zip)
  File "/home/user/.local/lib/python3.8/site-packages/cmake_init_lib/cmake_init.py", line 299, in create
    d = get_substitutes(args, os.path.basename(path))
  File "/home/user/.local/lib/python3.8/site-packages/cmake_init_lib/cmake_init.py", line 133, in get_substitutes
    "std": ask(
  File "/home/user/.local/lib/python3.8/site-packages/cmake_init_lib/cmake_init.py", line 83, in ask
    return prompt(*args, **kwargs, no_prompt=no_prompt)
  File "/home/user/.local/lib/python3.8/site-packages/cmake_init_lib/cmake_init.py", line 61, in prompt
    raise ValueError()
ValueError

```

**Comment by friendlyanon** [comment]
You have to specify just the standard version, not the language. The language by default is C++ with a switch for C using `--c`. So specifying C++17 is just `cmake-init --std 17 <path>`. C++17 is the default for C++ mode anyway. Would that line in the help be better like this?
```
  --std <std>      set the language standard to use (defaults: C - 99, C++ - 17)
```

**Comment by willwray** [comment]
Thanks, and yes; examples for the default value in the `--help` would be, helpful
(with the `--std` flag being so similar to the compiler's `-std` flag).

I can confirm it completes cleanly for me with `--std 20`.
Now to take it for a spin.

**Comment by friendlyanon** [comment]
Does this look better? https://github.com/friendlyanon/cmake-init/commit/e1c067e9992dc8ea205f435483703d992c132b91
```
  --std NN         set the language standard to use (defaults: C++ - 17, C - 99)
```

**Comment by friendlyanon** [comment]
Improved in v0.20.5

**Comment by willwray** [comment]
Thank you, yes; that does look better.
